language: node_js

node_js:
  - "0.10"
  - "0.8"

env:
  - NUODB_VERSION=2.2.0.9 NUODB_ADD_DOMAIN_PASS=yes NUODB_START_AGENT=yes
  - NUODB_VERSION=2.1.1.10 NUODB_ADD_DOMAIN_PASS=yes NUODB_START_AGENT=yes
  - NUODB_VERSION=2.0.4.24 NUODB_ADD_DOMAIN_PASS=no NUODB_START_AGENT=no
  
notifications:
  recipients:
    - tgates@nuodb.com
    - vduda@nuodb.com
    - drivers@nuodb.com

before_install:
  - wget http://download.nuohub.org/nuodb_${NUODB_VERSION}_amd64.deb --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb
  - export NUODB_HOME=/opt/nuodb
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - if [[ "${NUODB_ADD_DOMAIN_PASS}" == "yes" ]] ; then sudo chmod 777 ${NUODB_HOME}/etc/default.properties; echo "domainPassword = bird" >> ${NUODB_HOME}/etc/default.properties; sudo chmod 600 ${NUODB_HOME}/etc/default.properties; fi
  - if [[ "${NUODB_START_AGENT}" == "yes" ]]; then sudo service nuoagent start; fi
  - sleep 10


before_script:
  - /opt/nuodb/bin/nuodbmgr --broker localhost --user domain --password bird --command "start process sm database test host localhost archive /var/opt/nuodb/production-archives/test initialize true waitForRunning true"
  - /opt/nuodb/bin/nuodbmgr --broker localhost --user domain --password bird --command "start process te database test host localhost options '--dba-user dba --dba-password goalie' waitForRunning true"
  - echo "create user cloud password 'user';" | ${NUODB_HOME}/bin/nuosql test@localhost --user dba --password goalie

after_script:
  - sudo dpkg -r nuodb
